apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: gpa-validator
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: ${CA_BUNDLE}
      service:
        namespace: kube-system
        name: gpa-validator
        path: /mutate
    failurePolicy: Ignore
    name: gpa-validator.autoscaling.ocgi.dev
    namespaceSelector:
      matchExpressions:
        - key: ns
          operator: NotIn
          values:
            - kube-system
    rules:
      - apiGroups:
          - "autoscaling.ocgi.dev"
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - '*'
        scope: '*'
    sideEffects: None
    timeoutSeconds: 10
